export const cryptoData = [
  {
    id: 1,
    name: 'Bitcoin',
    symbol: 'BTC',
    price: '$118,887',
    change: '+2.4%',
    isPositive: true,
    color: '#F7931A',
    icon: '₿',
  },
  {
    id: 2,
    name: 'Ethereum',
    symbol: 'ETH',
    price: '$3,348',
    change: '-1.2%',
    isPositive: false,
    color: '#627EEA',
    icon: 'Ξ',
  },
  {
    id: 3,
    name: 'Cardano',
    symbol: 'ADA',
    price: '$0.80',
    change: '+2.97%',
    isPositive: true,
    color: '#0033AD',
    icon: '₳',
  },
  {
    id: 4,
    name: 'Solana',
    symbol: 'SOL',
    price: '$184.62',
    change: '+4.12%',
    isPositive: true,
    color: '#00D18C',
    icon: '◎',
  },
  {
    id: 5,
    name: 'XRP',
    symbol: 'XRP',
    price: '$3.13',
    change: '+3.82%',
    isPositive: true,
    color: '#23292F',
    icon: 'X',
  },
  {
    id: 6,
    name: 'Polkadot',
    symbol: 'DOT',
    price: '$3.82',
    change: '-2.11%',
    isPositive: false,
    color: '#E6007A',
    icon: '●',
  },
  {
    id: 7,
    name: 'Avalanche',
    symbol: 'AVAX',
    price: '$23.40',
    change: '-3.07%',
    isPositive: false,
    color: '#E84142',
    icon: '▲',
  },
  {
    id: 8,
    name: 'Polygon',
    symbol: 'MATIC',
    price: '$0.21',
    change: '-4.94%',
    isPositive: false,
    color: '#8247E5',
    icon: '⬟',
  },
  {
    id: 9,
    name: 'TRON',
    symbol: 'TRX',
    price: '$0.32',
    change: '-3.60%',
    isPositive: false,
    color: '#FF060A',
    icon: '▼',
  },
  {
    id: 10,
    name: 'Litecoin',
    symbol: 'LTC',
    price: '$108.19',
    change: '-0.73%',
    isPositive: false,
    color: '#BFBBBB',
    icon: 'Ł',
  },
];