export const cryptoData = [
  {
    id: 1,
    name: 'Bitcoin',
    symbol: 'BTC',
    price: '$118,887',
    change: '+2.4%',
    isPositive: true,
    color: '#FFEDD5',
    icon: '₿',
  },
  {
    id: 2,
    name: 'Ethereum',
    symbol: 'ETH',
    price: '$3,348',
    change: '-1.2%',
    isPositive: false,
    color: '#DBEAFE',
    icon: 'Ξ',
  },
  {
    id: 3,
    name: 'Cardano',
    symbol: 'ADA',
    price: '$0.80',
    change: '+2.97%',
    isPositive: true,
    color: '#DBEAFE',
    icon: '₳',
  },
  {
    id: 4,
    name: 'Solana',
    symbol: 'SOL',
    price: '$184.62',
    change: '+4.12%',
    isPositive: true,
    color: '#E4DCFC',
    icon: '◎',
  },
  {
    id: 5,
    name: 'XRP',
    symbol: 'XRP',
    price: '$3.13',
    change: '+3.82%',
    isPositive: true,
    color: '#D9D9D9',
    icon: 'X',
  },
  {
    id: 6,
    name: 'Polkadot',
    symbol: 'DOT',
    price: '$3.82',
    change: '-2.11%',
    isPositive: false,
    color: '#FCDCF6',
    icon: '●',
  },
  {
    id: 7,
    name: 'Avalanche',
    symbol: 'AVAX',
    price: '$23.40',
    change: '-3.07%',
    isPositive: false,
    color: '#FCDCDD',
    icon: '▲',
  },
  {
    id: 8,
    name: 'Polygon',
    symbol: 'MATIC',
    price: '$0.21',
    change: '-4.94%',
    isPositive: false,
    color: '#E8DCFC',
    icon: '⬟',
  },
  {
    id: 9,
    name: 'TRON',
    symbol: 'TRX',
    price: '$0.32',
    change: '-3.60%',
    isPositive: false,
    color: '#FCDCDC',
    icon: '▼',
  },
  {
    id: 10,
    name: 'Litecoin',
    symbol: 'LTC',
    price: '$108.19',
    change: '-0.73%',
    isPositive: false,
    color: '#DCEFFC',
    icon: 'Ł',
  },
];

/*
INSERT INTO public.coins (name, symbol, color)
VALUES
  ('Bitcoin', 'BTC', '#FFEDD5'),
  ('Ethereum', 'ETH', '#DBEAFE'),
  ('Tether', 'USDT', '#D4F1E8'),
  ('BNB', 'BNB', '#F3BA2F'),
  ('Solana', 'SOL', '#E4DCFC'),
  ('USD Coin', 'USDC', '#D6E6FA'),
  ('XRP', 'XRP', '#D9D9D9'),
  ('Cardano', 'ADA', '#DBEAFE'),
  ('Dogecoin', 'DOGE', '#F5E6A7'),
  ('TRON', 'TRX', '#FF4B4B'),
  ('Avalanche', 'AVAX', '#FAD4D4'),
  ('Shiba Inu', 'SHIB', '#FFD1C7'),
  ('Polkadot', 'DOT', '#FCE4EC'),
  ('Chainlink', 'LINK', '#D6E6FA'),
  ('Bitcoin Cash', 'BCH', '#D4F1E8'),
  ('NEAR Protocol', 'NEAR', '#E6ECEF'),
  ('Polygon', 'MATIC', '#E4DCFC'),
  ('Litecoin', 'LTC', '#E6ECEF'),
  ('Internet Computer', 'ICP', '#F5E6FA'),
  ('Uniswap', 'UNI', '#FAD4E8'),
  ('Dai', 'DAI', '#FFF8E1'),
  ('Cosmos', 'ATOM', '#E6ECEF'),
  ('Stellar', 'XLM', '#D6E6FA'),
  ('Monero', 'XMR', '#FFE0CC'),
  ('Ethereum Classic', 'ETC', '#D4F1E8'),
  ('Hedera', 'HBAR', '#E6ECEF'),
  ('Filecoin', 'FIL', '#D6E6FA'),
  ('Aptos', 'APT', '#D9E8F5'),
  ('Arbitrum', 'ARB', '#D6E6FA'),
  ('Hyperliquid', 'HYPE', '#E4DCFC');
*/